hedera:
 mirror:
   importer:
     downloader:
       accessKey: minioadmin
       cloudProvider: "S3"
       secretKey: minioadmin
       bucketName: hedera-streams
       endpointOverride: http://minio:9000
     initialAddressBook: "/usr/etc/hedera-mirror-importer/local-dev-1-node.addressbook.f102.json.bin"
     network: OTHER
#    monitor:
#      operator:
#        accountId: {accountId}
#        privateKey: {privateKey}
#      publish:
#        connections: 4
#        scenarios:
#          - name: HCS pinger
#            properties:
#              topicId: {topicId}
#            tps: 1
#            type: CONSENSUS_SUBMIT_MESSAGE
